# Generated by Django 5.1.7 on 2025-04-02 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('equipo_danado', 'Equipo dañado'), ('acoso', 'Acoso'), ('bullying', 'Bullying'), ('reclamo', 'Reclamo'), ('coordinacion', 'Contacto con coordinación')], max_length=30)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('laboratorio', models.CharField(blank=True, max_length=100, null=True)),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='evidencias/')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
