# Generated by Django 5.1.7 on 2025-04-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='comuna',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
